#!/usr/bin/env node
// Copies the app's pure engine files (and every file they import) from apps/ipad into engines/app/,
// then writes engines/index.js listing the engines that exist. Run it before every deploy:
//   node server/guard/sync.mjs            (from the repo root, or from anywhere)
//   node server/guard/sync.mjs --bundle   (also writes dist/worker.js — ONE file for the dashboard editor; needs esbuild)
// Engines whose file is missing (a module not written yet) are skipped — the app then uses its local one.
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync } from "node:fs";
import { dirname, join, resolve, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = resolve(HERE, "../../apps/ipad");
const OUT = join(HERE, "engines/app");

// name → file in apps/ipad + how the server calls it (a = the args array the app sent, c = {maxMs})
export const LIST = [
  { name: "optimize", file: "engine/cut/cutOptimizer.js", as: "cut", run: "cut.optimize(a[0], capT(a[1], c))", about: "رص القطع على الألواح (نفس محرك الجهاز)" },
  { name: "cutGroups", file: "engine/cut/cutOptimizer.js", as: "cut", run: "(a[0] || []).map((g) => ({ key: g.key, result: cut.optimize(g.parts, capT({ ...a[1], ...(g.sheetW ? { sheetW: g.sheetW, sheetH: g.sheetH } : {}), remnants: g.remnants || [] }, c)) }))", about: "خطة قص كاملة لكل الخامات (زي cutworker.js)" },
  { name: "price", file: "modules/guard/price.js", as: "price", run: "price.priceQuote(a[0])", about: "معادلات التسعير" },
  { name: "cutfitSearch", file: "modules/cutfit/engine.js", as: "cutfit", run: "cutfit.cutfitSearch(...a, c)", about: "التصميم الواعي بالقص (موديول 1)" },
  { name: "autogenRank", file: "modules/autogen/engine.js", as: "autogen", run: "autogen.autogenRank(...a, c)", about: "ترتيب التصميمات التلقائية (موديول 3)" },
];

const IMP = /(?:import|export)\s*(?:[^'"]*?\sfrom\s*)?['"](\.{1,2}\/[^'"]+)['"]|import\(\s*['"](\.{1,2}\/[^'"]+)['"]\s*\)/g;
function copyTree(rel, seen) {
  if (seen.has(rel)) return;
  seen.add(rel);
  const src = join(APP, rel);
  const code = readFileSync(src, "utf8");
  if (/\b(document|window|localStorage)\s*\./.test(code.replace(/\/\/.*|\/\*[\s\S]*?\*\//g, ""))) console.warn(`⚠ ${rel} بيلمس document/window — المحرك لازم يكون pure`);
  mkdirSync(dirname(join(OUT, rel)), { recursive: true });
  writeFileSync(join(OUT, rel), code);
  for (const m of code.matchAll(IMP)) copyTree(relative(APP, resolve(dirname(src), m[1] || m[2])).split("\\").join("/"), seen);
}

export function sync({ quiet = false } = {}) {
  rmSync(OUT, { recursive: true, force: true });
  const seen = new Set(), have = [];
  for (const e of LIST) {
    if (!existsSync(join(APP, e.file))) { if (!quiet) console.log(`– ${e.name}: ${e.file} مش موجود (اتساب)`); continue; }
    copyTree(e.file, seen);
    have.push(e);
  }
  const imports = [...new Map(have.map((e) => [e.as, `import * as ${e.as} from "./app/${e.file}";`])).values()];
  const src = `// GENERATED by server/guard/sync.mjs — do not edit by hand (run: node server/guard/sync.mjs)
import { hello } from "./example.js";
${imports.join("\n")}
/** the time a heavy engine may spend (seconds), never more than the server allows */
const capT = (o = {}, c = {}) => ({ ...(o || {}), timeCap: Math.max(0.05, Math.min(+(o || {}).timeCap || 6, (c.maxMs || 8000) / 1000)) });
export const ENGINES = {
  hello: { run: (a) => hello(a[0]), about: "مثال" },
${have.map((e) => `  ${e.name}: { run: (a, c) => ${e.run}, about: ${JSON.stringify(e.about)} },`).join("\n")}
};
`;
  writeFileSync(join(HERE, "engines/index.js"), src);
  if (!quiet) console.log(`✓ engines: hello, ${have.map((e) => e.name).join(", ")} · ${seen.size} files copied`);
  return have.map((e) => e.name);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  sync();
  if (process.argv.includes("--bundle")) {
    const cands = [process.env.ESBUILD, "esbuild", "/opt/npm-tools/node_modules/esbuild/bin/esbuild"].filter(Boolean);
    mkdirSync(join(HERE, "dist"), { recursive: true });
    let done = false;
    for (const bin of cands) {
      try { execFileSync(bin, [join(HERE, "worker.js"), "--bundle", "--format=esm", "--platform=neutral", "--minify", `--outfile=${join(HERE, "dist/worker.js")}`], { stdio: "inherit" }); done = true; break; } catch { /* next */ }
    }
    if (!done) { console.error("esbuild مش موجود — استخدم npx wrangler deploy (بيجمّع لوحده)"); process.exit(1); }
    console.log("✓ dist/worker.js (ملف واحد — ينفع يتلزق في محرر Cloudflare)");
  }
}
