exec(open("scnW.py").read())
tap("[data-wc=splitv]"); pg.wait_for_timeout(500)
tap(".wcask input"); pg.wait_for_timeout(300)
for ch in "60,240": tap(f".kpad.on button:text-is('{ch}')", w=150)
tap(".wcask [data-go]"); pg.wait_for_timeout(600)
tap("[data-wckind=open]"); tap("[data-wctog=led]")
tap("[data-wcpath='2']"); tap("[data-wckind=open]"); tap("[data-wctog=led]")
tap("[data-wcpath='1']"); tap("[data-wc=splith]"); pg.wait_for_timeout(400)
tap(".wcask input"); pg.wait_for_timeout(300)
for ch in "80,130": tap(f".kpad.on button:text-is('{ch}')", w=150)
tap(".wcask [data-go]"); pg.wait_for_timeout(600)
tap("[data-wckind=solid]")
tap("[data-wcpath='1.1']"); tap("[data-wckind=device]")
tap("[data-wcpath='1.2']"); tap("[data-wckind=drawers]")
