# precompute the zero-waste library with the default sheet settings → apps/ipad/zwlib.js
import asyncio, subprocess, sys, time, json
from playwright.async_api import async_playwright
srv = subprocess.Popen([sys.executable, "-m", "http.server", "8829"], cwd="/home/claude/novera-app/dist/pwa", stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(0.8)
async def main():
  async with async_playwright() as p:
    b = await p.chromium.launch(args=["--use-angle=swiftshader", "--enable-unsafe-swiftshader"])
    pg = await (await b.new_context(viewport={"width": 1180, "height": 900})).new_page(); ev = pg.evaluate; W = pg.wait_for_timeout
    errs=[]; pg.on("pageerror", lambda e: errs.append(str(e)))
    await pg.goto("http://localhost:8829/index.html"); await W(3000)
    try: await ev("localStorage.clear(); caches.keys().then(ks=>Promise.all(ks.map(k=>caches.delete(k))))")
    except Exception as e: pass
    await W(1500); await pg.reload(); await W(6000)
    await ev("window.__dbg.state.tourDone=true; document.querySelector('[data-hlast]')?.click()"); await W(1200)
    await ev("window.__dbg.state.project.units=[]; window.__dbg.state.libOpen=true; window.__dbg.render(true)"); await W(1000)
    sig = await ev("window.__dbg.zwLibStore().st.sig")
    print("sig", sig)
    specs = await ev("window.__dbg.ZW_LIB")
    items = {}
    for sp in specs:
      t0=time.time()
      r = await ev("""async (sp)=>{ const r = await window.__dbg.zwSolve({mode:sp.mode, counts:{carcass:{n:sp.carcass},front:{n:sp.front||0},back:{n:0}}, budget:45000, onProgress:()=>{}}); return { list: r.list.map(x=>({set:x.set.map(i=>({k:i.c.k,w:i.w,sh:i.sh})), waste:x.waste, used:x.used, leftovers:x.leftovers})), tried:r.tried, secs:r.secs }; }""", sp)
      items[sp["id"]] = r
      best = r["list"][0] if r["list"] else None
      print(sp["id"], round(time.time()-t0,1), "s", "tried", r["tried"], "best", best and (round(best["waste"]*100,1), [f"{q['k']}:{q['w']}+{q['sh']}" for q in best["set"]]))
    out = {"sig": sig, "items": items, "at": int(time.time())}
    open("/home/claude/novera-app/apps/ipad/zwlib.js","w").write("// precomputed zero-waste library — generated by scratchpad/lib/zwpre.py (sheet 244×122, kerf 4 mm, trim 1 cm, NOVERA shelf rules), do not edit by hand\nexport default " + json.dumps(out, ensure_ascii=False) + ";\n")
    print(errs[:5])
    await b.close()
asyncio.run(main()); srv.terminate()
