# Generates packages/engine/src/kitchen/config.ts from the plugin's lib/config.rb (Config module).
# Run after the plugin changes its defaults: ruby parity/ruby/gen_kitchen_config.rb
require "json"
require_relative "sketchup_fake/sketchup_fake"
KUD_PLUGIN = ENV["KUD_PLUGIN"] || "/home/claude/kud/kitchen_unit_designer"
require File.join(KUD_PLUGIN, "lib/config")
c = KitchenUnitDesigner::Config
out = +"// GENERATED by parity/ruby/gen_kitchen_config.rb from the plugin's lib/config.rb — do not edit.\n"
out << "export const EXTENSION_VERSION = #{c::EXTENSION_VERSION.to_json};\n"
out << "export const MIN_DIMENSION_CM = #{c::MIN_DIMENSION_CM};\n"
out << "export const HINGE_CUP_DEPTH_CM = #{c::HINGE_CUP_DEPTH_CM};\n"
out << "export const FRONT_THICKNESS_CM = #{c::FRONT_THICKNESS_CM};\n"
out << "export const COLORS = {\n"
c::COLORS.each { |k, v| out << "  #{k}: #{v.to_json} as [number, number, number],\n" }
out << "} as const;\n\n"
out << "/** Config::DEFAULTS — the kitchen design dialog's initial values */\n"
out << "export const DEFAULTS: Record<string, unknown> = {\n"
c::DEFAULTS.each { |k, v| out << "  #{k.to_json}: #{v.to_json},\n" }
out << "};\n"
File.write(File.join(__dir__, "../../packages/engine/src/kitchen/config.ts"), out)
puts "config.ts: #{c::DEFAULTS.size} defaults"
